# Configuration du serveur
sonar.host.url=http://localhost:9000
sonar.token=sqp_7dcc2520d1495f6570c0e6c2870b1cc392f3c2f8

# Identification du projet
sonar.projectKey=PriceWise_Sonar
sonar.projectName=PriceWise_Sonar

# Chemins à analyser (relativement à l'emplacement du fichier)
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclusions pour Angular / Node
sonar.exclusions=node_modules/**, .angular/**, dist/**, **/*.spec.ts
